export const MOODS = [
    { label: "mood_happy", emoji: "😊", color: "#10B981" },
    { label: "mood_stressed", emoji: "😰", color: "#F59E0B" },
    { label: "mood_sad", emoji: "😢", color: "#3B82F6" },
    { label: "mood_tired", emoji: "😴", color: "#6366F1" },
    { label: "mood_neutral", emoji: "😐", color: "#6B7280" },
];

export const ALL_CARDS = [
    // BIBLE
    { id: "1", title: "Dieu est avec toi", title_en: "God is with you", source: "bible", emoji: "📖", reference: "Josué 1:9", fullText: "Ne t'ai-je pas donné cet ordre : Fortifie-toi et prends courage ? Ne t'effraie point et ne t'épouvante point, car l'Éternel, ton Dieu, est avec toi dans tout ce que tu entreprendras.", fullText_en: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
    { id: "4", title: "La paix vient de l'intérieur", title_en: "Peace comes from within", source: "bible", emoji: "☮️", reference: "Jean 14:27", fullText: "Je vous laisse la paix, je vous donne ma paix. Je ne vous donne pas comme le monde donne. Que votre cœur ne se trouble point, et ne s'alarme point.", fullText_en: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid." },
    { id: "7", title: "L'Éternel est mon berger", title_en: "The Lord is my shepherd", source: "bible", emoji: "🐑", reference: "Psaume 23:1-3", fullText: "L'Éternel est mon berger : je ne manquerai de rien. Il me fait reposer dans de verts pâturages, il me dirige près des eaux paisibles. Il restaure mon âme, il me conduit dans les sentiers de la justice, à cause de son nom.", fullText_en: "The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul." },
    { id: "8", title: "Soyez forts et courageux", title_en: "Be strong and courageous", source: "bible", emoji: "🦁", reference: "Deutéronome 31:6", fullText: "Fortifiez-vous et ayez du courage ! Ne craignez point et ne soyez point effrayés devant eux ; car l'Éternel, ton Dieu, lui-même marchera avec toi, il ne te délaissera point, il ne t'abandonnera point.", fullText_en: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you." },
    { id: "9", title: "L'amour est patient", title_en: "Love is patient", source: "bible", emoji: "❤️", reference: "1 Corinthiens 13:4-7", fullText: "L'amour est patient, il est plein de bonté ; l'amour n'est point envieux ; l'amour ne se vante point, il ne s'enfle point d'orgueil. Il ne fait rien de malhonnête, il ne cherche point son intérêt, il ne s'irrite point, il ne soupçonne point le mal.", fullText_en: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs." },
    { id: "10", title: "Tout est possible à celui qui croit", title_en: "Everything is possible for one who believes", source: "bible", emoji: "✨", reference: "Marc 9:23", fullText: "Jésus lui dit : Si tu peux !... Tout est possible à celui qui croit.", fullText_en: "\"If you can?\" said Jesus. \"Everything is possible for one who believes.\"" },

    // CORAN
    { id: "2", title: "Ne désespère jamais", title_en: "Never despair", source: "coran", emoji: "📚", reference: "Sourate Az-Zumar 39:53", fullText: "Dis : \"Ô Mes serviteurs qui avez commis des excès à votre propre détriment, ne désespérez pas de la miséricorde d'Allah. Car Allah pardonne tous les péchés. Oui, c'est Lui le Pardonneur, le Très Miséricordieux.\"", fullText_en: "Say: 'O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.'" },
    { id: "5", title: "Cherche la lumière", title_en: "Seek the light", source: "coran", emoji: "💡", reference: "Sourate An-Nur 24:35", fullText: "Allah est la Lumière des cieux et de la terre. Sa lumière est semblable à une niche où se trouve une lampe. La lampe est dans un (récipient de) cristal et celui-ci ressemble à un astre de grand éclat.", fullText_en: "Allah is the Light of the heavens and the earth. The example of His light is like a niche within which is a lamp, the lamp is within glass, the glass as if it were a brilliant star." },
    { id: "11", title: "Après la difficulté vient la facilité", title_en: "After hardship comes ease", source: "coran", emoji: "🌈", reference: "Sourate Ash-Sharh 94:5-6", fullText: "À côté de la difficulté est, certes, une facilité ! À côté de la difficulté est, certes, une facilité !", fullText_en: "For indeed, with hardship will be ease. Indeed, with hardship will be ease." },
    { id: "12", title: "Allah ne charge nulle âme au-dessus de sa capacité", title_en: "Allah does not burden a soul beyond that it can bear", source: "coran", emoji: "⚖️", reference: "Sourate Al-Baqara 2:286", fullText: "Allah n'impose à aucune âme une charge supérieure à sa capacité. Elle sera récompensée du bien qu'elle aura fait, punie du mal qu'elle aura fait.", fullText_en: "Allah does not burden a soul beyond that it can bear. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned." },
    { id: "13", title: "Et Il est avec vous où que vous soyez", title_en: "And He is with you wherever you are", source: "coran", emoji: "🤲", reference: "Sourate Al-Hadid 57:4", fullText: "C'est Lui qui a créé les cieux et la terre en six jours puis Il S'est établi sur le Trône. Il sait ce qui pénètre dans la terre et ce qui en sort, ce qui descend du ciel et ce qui y monte, et Il est avec vous où que vous soyez. Et Allah observe parfaitement ce que vous faites.", fullText_en: "It is He who created the heavens and earth in six days and then established Himself above the Throne. He knows what penetrates into the earth and what emerges from it and what descends from the heaven and what ascends therein; and He is with you wherever you are." },
    { id: "14", title: "Le rappel profite aux croyants", title_en: "Reminder benefits the believers", source: "coran", emoji: "🔔", reference: "Sourate Adh-Dhariyat 51:55", fullText: "Et rappelle ; car le rappel profite aux croyants.", fullText_en: "And remind, for indeed, the reminder benefits the believers." },

    // AFRICAN TEXTS
    { id: "3", title: "Proverbe africain positif", title_en: "Positive African Proverb", source: "african", emoji: "🌍", reference: "Proverbe Mandingue", fullText: "Quelle que soit la durée de la nuit, le soleil finit toujours par se lever. Ce proverbe nous enseigne la patience et l'espérance face aux épreuves de la vie.", fullText_en: "No matter how long the night, the sun will always rise. This proverb teaches us patience and hope in the face of life's trials." },
    { id: "6", title: "L'ubuntu : je suis parce que nous sommes", title_en: "Ubuntu: I am because we are", source: "african", emoji: "🤝", reference: "Philosophie Ubuntu – Afrique du Sud", fullText: "\"Je suis ce que je suis grâce à ce que nous sommes tous.\" L'ubuntu est une philosophie humaniste sud-africaine qui signifie que notre humanité est liée les uns aux autres. Être humain, c'est reconnaître l'humanité des autres.", fullText_en: "\"I am what I am because of who we all are.\" Ubuntu is a South African humanist philosophy meaning that our humanity is tied to one another. To be human is to recognize the humanity of others." },
    { id: "15", title: "Seul on va plus vite, ensemble on va plus loin", title_en: "Alone we go faster, together we go further", source: "african", emoji: "👣", reference: "Proverbe Africain", fullText: "Ce proverbe met en lumière la force de la solidarité et de la coopération. Si l'individu peut agir rapidement seul, c'est ensemble que les plus grands accomplissements sont possibles.", fullText_en: "This proverb highlights the strength of solidarity and cooperation. While an individual can act quickly alone, the greatest accomplishments are possible together." },
    { id: "16", title: "Le fleuve fait des détours car personne ne lui montre le chemin", title_en: "The river twists because no one shows it the way", source: "african", emoji: "🌊", reference: "Proverbe Bambara – Mali", fullText: "Le fleuve fait des détours parce que personne ne lui montre le chemin. Ce proverbe nous rappelle l'importance du mentorat et de la guidance dans la vie.", fullText_en: "The river twists because no one shows it the way. This proverb reminds us of the importance of mentorship and guidance in life." },
    { id: "17", title: "La persévérance est un talisman", title_en: "Perseverance is a talisman", source: "african", emoji: "💎", reference: "Proverbe Peul", fullText: "La persévérance est un talisman pour la vie. Celui qui s'accroche à ses objectifs avec ténacité finira par triompher de tous les obstacles.", fullText_en: "Perseverance is a talisman for life. Those who cling to their goals with tenacity will eventually triumph over all obstacles." },
    { id: "18", title: "Un arbre qui tombe fait plus de bruit qu'une forêt qui pousse", title_en: "A falling tree makes more noise than a growing forest", source: "african", emoji: "🌳", reference: "Proverbe Africain", fullText: "Un arbre qui tombe fait plus de bruit qu'une forêt qui pousse. Ce proverbe nous invite à ne pas nous concentrer sur le négatif mais à voir la croissance silencieuse du bien autour de nous.", fullText_en: "A falling tree makes more noise than a growing forest. This proverb invites us not to focus on the negative but to see the silent growth of good around us." },
    { id: "19", title: "Si tu veux savoir la fin, regarde le commencement", title_en: "If you want to know the end, look at the beginning", source: "african", emoji: "👀", reference: "Proverbe Wolof – Sénégal", fullText: "Si tu veux savoir la fin, regarde le commencement. Les fondations que nous posons aujourd'hui déterminent la qualité de ce que nous construirons demain.", fullText_en: "If you want to know the end, look at the beginning. The foundations we lay today determine the quality of what we will build tomorrow." },
    { id: "20", title: "Le savoir est une forêt", title_en: "Knowledge is a forest", source: "african", emoji: "🧠", reference: "Proverbe Bambara – Mali", fullText: "Le savoir est comme une forêt : personne ne peut en faire le tour seul. Ce proverbe enseigne l'humilité intellectuelle et la valeur du partage des connaissances.", fullText_en: "Knowledge is like a forest: no one can go around it alone. This proverb teaches intellectual humility and the value of sharing knowledge." },
];

export const MOOD_ICONS: { [key: string]: string } = {
    happy: "😊",
    calm: "😌",
    anxious: "😟",
    stressed: "😰",
};
